# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 2.17.95.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
  - master

  # blacklist
  except:
  - gh-pages

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

image:
  - Visual Studio 2017
#  - Visual Studio 2015

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
#platform: Any CPU

# to add several platforms to build matrix:
platform:
  - Win32
  - x64

# build Configuration, i.e. Debug, Release, etc.
#configuration: Release

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
#  - ps: Update-AppveyorBuild -Version "2.$(Get-Date -format yy.Md).$env:appveyor_build_number"
  - ps: |
      if ($true) 
      {
        $Major = 2
        $Minor = $(Get-Date -format yy)
        $Revis = $(Get-Date -format Mdd)
        $Build = $env:appveyor_build_number
        if (!$Build) { $Build = 0 }
        $SciVer = Get-Content "scintilla\version.txt"
        if (!$SciVer) { $SciVer = 0 }
        $CompleteVer = "$Major.$Minor.$Revis.$Build"
        Copy-Item -LiteralPath "Versions\VersionEx.h.tpl" -Destination "src\VersionEx.h" -Force
        (Get-Content "src\VersionEx.h") | ForEach-Object { $_ -replace '\$MAJOR\$', "$Major" } | Set-Content "src\VersionEx.h"
        (Get-Content "src\VersionEx.h") | ForEach-Object { $_ -replace '\$MINOR\$', "$Minor" } | Set-Content "src\VersionEx.h"
        (Get-Content "src\VersionEx.h") | ForEach-Object { $_ -replace '\$MAINT\$', "$Revis" } | Set-Content "src\VersionEx.h"
        (Get-Content "src\VersionEx.h") | ForEach-Object { $_ -replace '\$BUILD\$', "$Build" } | Set-Content "src\VersionEx.h"
        (Get-Content "src\VersionEx.h") | ForEach-Object { $_ -replace '\$SCIVER\$', "$SciVer" } | Set-Content "src\VersionEx.h"
        Copy-Item -LiteralPath "Versions\Notepad3.exe.manifest.tpl" -Destination "res\Notepad3.exe.manifest.conf" -Force
        (Get-Content "res\Notepad3.exe.manifest.conf") | ForEach-Object { $_ -replace '\$VERSION\$', $CompleteVer } | Set-Content "res\Notepad3.exe.manifest.conf"
      }

assembly_info:
  patch: true
  #file: '**\AssemblyInfo.*'
  file: 'Versions\AssemblyInfo.inf'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

# to add several configurations to build matrix:
configuration:
  - Release
#  - Debug

build:
  project: Notepad3.sln
  parallel: true
  verbosity: minimal
test: off

# Artifact paths are relative to C:\projects\notepad3\
artifacts:
  - path: bin\**\*.exe
#  - name: All

matrix:
  fast_finish: true

after_build:
#  - 7z a Notepad3_%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Output\%CONFIGURATION%\Notepad3.exe
#  - appveyor PushArtifact Notepad3_%APPVEYOR_BUILD_VERSION%.zip
 
#deploy:
#  - provider: S3
#  access_key_id: XXXXXXXXXXXXXXXXXXXX
#  secret_access_key:
#    secure: ---------------------------------------------------------
#  region: us-west-2
#  bucket: notepad3
#  artifact: All
#  set_public: true
#  encrypt: true
#notifications:
#- provider: Email
#  to:
#  - rizonesoft+github@gmail.com
#  on_build_success: true
#  on_build_failure: true
#  on_build_status_changed: true
